### ISSUE TITLE
Merge into faexport? 

### ISSUE THREAD

**Issue by Deer-Spangle** [highcup/faexport-container#1]
Hello,

I can't find any other contact for you, so hopefully this issue makes it's way to your attention. 
I'm maintaining a fork of faexport now, as boothale seems to be MIA, and I'm wondering if I can merge this into it?
http://github.com/Deer-Spangle/faexport is my fork, and I've got a rough Docker file set up, but it's using a separate image for redis. Your solution seems neater for user deployment though.
May I merge it in? 

Many thanks, 
Deer Spangle

**Comment by highcup** [comment]
I have submitted a pull request to https://github.com/Deer-Spangle/faexport adding the ability to run an internal redis instance.
